-- Lightweight per-user sync/audit events for support and live sync diagnostics.
-- Users can only read/insert their own events; Edge Functions can insert via service role.

create table if not exists public.planner_sync_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  source_platform text not null default 'web',
  event_type text not null,
  status text not null,
  duration_ms integer,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists planner_sync_events_user_created_at_idx
  on public.planner_sync_events (user_id, created_at desc);

alter table public.planner_sync_events enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'planner_sync_events'
      and policyname = 'planner_sync_events_select_own'
  ) then
    create policy planner_sync_events_select_own
      on public.planner_sync_events
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'planner_sync_events'
      and policyname = 'planner_sync_events_insert_own'
  ) then
    create policy planner_sync_events_insert_own
      on public.planner_sync_events
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;
end$$;
