-- Stores a serialized planner snapshot per user (uploaded by mobile, read by web).
-- We keep this as JSONB initially to avoid schema churn while the planner is being ported to TypeScript.

create table if not exists public.planner_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists planner_snapshots_user_updated_at_idx
  on public.planner_snapshots (user_id, updated_at desc);

-- Allow the authenticated user to manage only their own snapshots.
alter table public.planner_snapshots enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'planner_snapshots'
      and policyname = 'planner_snapshots_select_own'
  ) then
    create policy planner_snapshots_select_own
      on public.planner_snapshots
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'planner_snapshots'
      and policyname = 'planner_snapshots_insert_own'
  ) then
    create policy planner_snapshots_insert_own
      on public.planner_snapshots
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'planner_snapshots'
      and policyname = 'planner_snapshots_update_own'
  ) then
    create policy planner_snapshots_update_own
      on public.planner_snapshots
      for update
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'planner_snapshots'
      and policyname = 'planner_snapshots_delete_own'
  ) then
    create policy planner_snapshots_delete_own
      on public.planner_snapshots
      for delete
      to authenticated
      using (auth.uid() = user_id);
  end if;
end$$;

-- Keep updated_at current.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_planner_snapshots_updated_at on public.planner_snapshots;
create trigger set_planner_snapshots_updated_at
before update on public.planner_snapshots
for each row
execute function public.set_updated_at();

