-- Extend planner_snapshots so web/mobile can share both the raw planning inputs
-- and the deterministic planner outputs generated by the BillPayer shared engine.
-- This keeps one planner source of truth while GitHub Pages remains a static client.

alter table public.planner_snapshots
  add column if not exists plan jsonb,
  add column if not exists source_platform text,
  add column if not exists source_app_version text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists planner_schema_version text not null default 'billpayer-shared-v1',
  add column if not exists planner_engine_version text;

comment on table public.planner_snapshots is
  'Canonical synced planner state for a user. snapshot = PlannerSnapshot input, plan = PlannerPlan output from BillPayer shared engine.';

comment on column public.planner_snapshots.snapshot is
  'Serialized PlannerSnapshot from BillPayer shared models.';

comment on column public.planner_snapshots.plan is
  'Serialized PlannerPlan computed by the canonical BillPayer shared planner.';

comment on column public.planner_snapshots.planner_schema_version is
  'Contract version for snapshot/plan JSON structure.';

comment on column public.planner_snapshots.planner_engine_version is
  'Version identifier for the planner engine that generated plan.';
